services:
  - type: web
    name: ia-exara-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=$PORT
